### **Exercise: Game of Life**

Implement [Conway's game of life](https://en.wikipedia.org/wiki/Conway%27s_Game_of_Life) using numpy array to hold data.
Neighbours are defined as adjacent cells (all the 8).

 - Any LIVING cell with 2 or 3 neighbours survives.
 - Any DEAD cell with 3 neighbours comes alive.
 - Any OTHER LIVING cell dies.
 - All deaths and births occur simultaneously

So, at each step you need:

 - calculate the number of neighnours
 - set "dead" or "alive" status according to the above
 - plot

### Hints and directions:

*Implement everything in a class*.

For initial conditions: two files "ships.txt" and "guns.txt" are provided in data folder (but feel free to create your own if you wish), you can read them like

```python
field=np.genfromtxt("ships.txt").transpose()
```

For plotting: Jupyter is very finicky with "real-time" plots and there is a high chance it will refuse to plot everything in one frame even if you try all the stackoverflow solutions, so I propose just using a script to run your program. Try the following code to produce "animation" to test that it works:

```python
import numpy as np
import matplotlib.pyplot as plt

plt.axis([0, 10, 0, 1])

for i in range(10):
    y = np.random.random()
    plt.scatter(i, y)
    plt.pause(0.5)
plt.show()

```

In [4]:
field=np.genfromtxt("./data/ships.txt").transpose()

In [5]:
print(field)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [14]:
field[0][23]

np.float64(0.0)

In [15]:
field.shape

(40, 64)

In [16]:
n = np.zeros_like(field)

In [19]:
n[1:, :] += field[:-1, :]

In [20]:
print(n[1:, :])

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [22]:
np.roll(field[1:, :], 1)

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(39, 64))